<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="54" started-at="2021-05-23T18:38:46Z" finished-at="2021-05-23T18:38:46Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="54" started-at="2021-05-23T18:38:46Z" finished-at="2021-05-23T18:38:46Z">
      <class name="Docker.Docker.parallelOneTest">
        <test-method status="FAIL" signature="initialize()[pri:0, instance:Docker.Docker.parallelOneTest@71248c21]" name="initialize" is-config="true" duration-ms="0" started-at="2021-05-23T20:38:46Z" finished-at="2021-05-23T20:38:46Z">
          <exception class="java.net.MalformedURLException">
            <message>
              <![CDATA[no protocol: 127.0.0.1:4444/wd/hub]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.net.MalformedURLException: no protocol: 127.0.0.1:4444/wd/hub
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at Docker.Docker.parallelOneTest.initialize(parallelOneTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.net.MalformedURLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="initialize()[pri:0, instance:Docker.Docker.parallelOneTest@71248c21]" name="initialize" is-config="true" duration-ms="0" started-at="2021-05-23T20:38:46Z" finished-at="2021-05-23T20:38:46Z">
          <exception class="java.net.MalformedURLException">
            <message>
              <![CDATA[no protocol: 127.0.0.1:4444/wd/hub]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.net.MalformedURLException: no protocol: 127.0.0.1:4444/wd/hub
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at Docker.Docker.parallelOneTest.initialize(parallelOneTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.net.MalformedURLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="SKIP" signature="parallelOne()[pri:0, instance:Docker.Docker.parallelOneTest@71248c21]" name="parallelOne" duration-ms="0" started-at="2021-05-23T20:38:46Z" finished-at="2021-05-23T20:38:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parallelOne -->
        <test-method status="SKIP" signature="paralleltwo()[pri:0, instance:Docker.Docker.parallelOneTest@71248c21]" name="paralleltwo" duration-ms="0" started-at="2021-05-23T20:38:46Z" finished-at="2021-05-23T20:38:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paralleltwo -->
        <test-method status="SKIP" signature="teardown()[pri:0, instance:Docker.Docker.parallelOneTest@71248c21]" name="teardown" is-config="true" duration-ms="0" started-at="2021-05-23T20:38:46Z" finished-at="2021-05-23T20:38:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="SKIP" signature="teardown()[pri:0, instance:Docker.Docker.parallelOneTest@71248c21]" name="teardown" is-config="true" duration-ms="0" started-at="2021-05-23T20:38:46Z" finished-at="2021-05-23T20:38:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Docker.Docker.parallelOneTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
